package com.vinpos.pos;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Hashtable;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinson
 */
public class Edit4course extends javax.swing.JDialog {

    /**
     * Creates new form EDITDialog
     */
    
    public Edit4course(java.awt.Frame parent, boolean modal, MyQuery q) {
        super(parent, modal);
        myQ = q;
        initComponents();
        
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
    }
    public boolean run(int oid, int tid, int aid){
        id=oid;
        tableID=tid;
        userID=aid;
        this.selectDB(oid);
        this.setVisible(true);
        return update;
        
    }

    public void selectDB(int oid){
        
        Hashtable<String, String> data = myQ.get4CourseDetailwithOid(oid);
            text1.setText(data.get("name"));
            text2.setText(data.get("firstCourse"));
            text8.setText(data.get("secondCourse"));
            text9.setText(data.get("thirdCourse"));
            text13.setText(data.get("price"));
            text4.setText(data.get("quantity"));
            text7.setText(data.get("subtable"));

            if(!data.get("position").equals("0")){
                    text6.setText(data.get("position"));
            }else{
                text6.setText("");
            }
      
    }
   

    public void updateDB(int oid){
        Hashtable<String, String> data= new Hashtable<String, String>();
        data.put("name", text1.getText());
        data.put("firstCourse", text2.getText());
        data.put("secondCourse", text8.getText());
        data.put("thirdCourse", text9.getText());
        data.put("price", text13.getText());
        data.put("quantity", text4.getText());
        data.put("subtable", text7.getText());
        data.put("position", text6.getText());
        myQ.update4CourseOrderWithTidOidAndHashedData(tableID, oid, data);
     
         
    }//end of editselect
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text4 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text8 = new javax.swing.JTextField();
        text9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text13 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lithos Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("4 COURSE EDIT PANEL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 490, 80));

        text1.setFont(new java.awt.Font("SimSun", 0, 14)); // NOI18N
        jPanel1.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 50));

        text2.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jPanel1.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 170, 40));

        jButton1.setFont(new java.awt.Font("Lithos Pro", 0, 36)); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 150, 60));

        jButton2.setFont(new java.awt.Font("Lithos Pro", 0, 36)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 200, 60));

        jLabel2.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel2.setText("item name on the check");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 20));

        jLabel3.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel3.setText("Soup or Side");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 140, 20));

        jLabel4.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel4.setText("Entree");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 110, 20));

        jLabel5.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel5.setText("quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 120, -1));

        text4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        text4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel1.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 90, 50));

        jLabel7.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel7.setText("seat");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 70, -1));

        text6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel1.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 80, 50));
        jPanel1.add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 80, 50));

        jLabel8.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel8.setText("check");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel9.setText("Appertizer");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 130, 20));

        text8.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jPanel1.add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 170, 40));

        text9.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        jPanel1.add(text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 170, 40));

        jLabel10.setFont(new java.awt.Font("Lithos Pro", 1, 18)); // NOI18N
        jLabel10.setText("Price");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));

        text13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        text13.setFont(new java.awt.Font("Lithos Pro", 1, 24)); // NOI18N
        jPanel1.add(text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.updateDB(id);
        update = true;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text1;
    private javax.swing.JFormattedTextField text13;
    private javax.swing.JTextField text2;
    private javax.swing.JFormattedTextField text4;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField text8;
    private javax.swing.JTextField text9;
    // End of variables declaration//GEN-END:variables

    private int id =0;
    int tableID;
    int userID;
    private MyQuery myQ;
    boolean update = false;
}
