package com.vinpos.pos;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sd
 */
public class FixMenu2 extends java.awt.Dialog {

    /**
     * Creates new form Edit
     */
    public FixMenu2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        //Toolkit tk = Toolkit.getDefaultToolkit();
        //Dimension screenSize = tk.getScreenSize();
        //final int WIDTH = screenSize.width;
        //final int HEIGHT = screenSize.height;
        //// Setup the frame accordingly
        //// This is assuming you are extending the JFrame //class
        //this.setLocation((WIDTH/3)+50, 0);
        
        
    }
    public void setJlabel(String s){
        jLabel1.setText(s);
    }

    public String[] getNameString(String s){
        setJlabel(s);
        setButton2();
        this.setVisible(true);
        return nameString;
    }



    public void setButton2(){
         jB1.setText("   Lobster PadThai");
         jB2.setText("   ");
         jB3.setText("   "); 
         jB4.setText("   ");
         jB5.setText("   ");
         jB6.setText("   ");
         jB7.setText("   ");
         jB8.setText("   ");
         jB9.setText("   ");
        jB10.setText("   ");
        jB11.setText("   Southeast(seafood)");
        jB12.setText("   House Pasta(seafood)");
        jB13.setText("   Garlic Shrimp Pasta");
        jB14.setText("   Classic Pasta(seafood)");
        jB15.setText("   Khao Soi(seafood)");
        jB16.setText("   Scallop Linguini");
        jB17.setText("   ");
        jB18.setText("   ");
        jB19.setText("   Clam");
        jB20.setText("   SP Crab");
        jB21.setText("   Lao Pie");
        jB22.setText("   Hen");
        jB23.setText("   Opaka");
        jB24.setText("   Salmon");
        jB25.setText("   Fisherman");
        jB26.setText("   Napoleon");
        jB27.setText("   Asian");
        jB28.setText("   Brioche");
        jB29.setText("   Ravioli");
        jB30.setText("   Lamb");
        
        
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB10 = new javax.swing.JButton();
        jB11 = new javax.swing.JButton();
        jB12 = new javax.swing.JButton();
        jB13 = new javax.swing.JButton();
        jB14 = new javax.swing.JButton();
        jB15 = new javax.swing.JButton();
        jB20 = new javax.swing.JButton();
        jB16 = new javax.swing.JButton();
        jB17 = new javax.swing.JButton();
        jB18 = new javax.swing.JButton();
        jB19 = new javax.swing.JButton();
        jB21 = new javax.swing.JButton();
        jB22 = new javax.swing.JButton();
        jB23 = new javax.swing.JButton();
        jB24 = new javax.swing.JButton();
        jB25 = new javax.swing.JButton();
        jB26 = new javax.swing.JButton();
        jB27 = new javax.swing.JButton();
        jB28 = new javax.swing.JButton();
        jB29 = new javax.swing.JButton();
        jB30 = new javax.swing.JButton();

        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 850));
        jPanel2.setPreferredSize(new java.awt.Dimension(920, 900));
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Touch to Delete");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 380, 70));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 150, 60));

        jB1.setBackground(new java.awt.Color(255, 255, 0));
        jB1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB1.setBorder(new javax.swing.border.MatteBorder(null));
        jB1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jPanel2.add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 50));

        jB2.setBackground(new java.awt.Color(255, 255, 0));
        jB2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB2.setBorder(new javax.swing.border.MatteBorder(null));
        jB2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        jPanel2.add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, 50));

        jB3.setBackground(new java.awt.Color(255, 255, 0));
        jB3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB3.setBorder(new javax.swing.border.MatteBorder(null));
        jB3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, 50));

        jB4.setBackground(new java.awt.Color(255, 255, 0));
        jB4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB4.setBorder(new javax.swing.border.MatteBorder(null));
        jB4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, 50));

        jB5.setBackground(new java.awt.Color(255, 255, 0));
        jB5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB5.setBorder(new javax.swing.border.MatteBorder(null));
        jB5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 50));

        jB6.setBackground(new java.awt.Color(255, 255, 0));
        jB6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB6.setBorder(new javax.swing.border.MatteBorder(null));
        jB6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 50));

        jB7.setBackground(new java.awt.Color(255, 255, 0));
        jB7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB7.setBorder(new javax.swing.border.MatteBorder(null));
        jB7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        jPanel2.add(jB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 190, 50));

        jB8.setBackground(new java.awt.Color(255, 255, 0));
        jB8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB8.setBorder(new javax.swing.border.MatteBorder(null));
        jB8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 190, 50));

        jB9.setBackground(new java.awt.Color(255, 255, 0));
        jB9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB9.setBorder(new javax.swing.border.MatteBorder(null));
        jB9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 190, 50));

        jB10.setBackground(new java.awt.Color(255, 255, 0));
        jB10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB10.setBorder(new javax.swing.border.MatteBorder(null));
        jB10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 190, 50));

        jB11.setBackground(new java.awt.Color(255, 217, 33));
        jB11.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB11.setBorder(new javax.swing.border.MatteBorder(null));
        jB11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB11ActionPerformed(evt);
            }
        });
        jPanel2.add(jB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, 50));

        jB12.setBackground(new java.awt.Color(255, 217, 33));
        jB12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB12.setBorder(new javax.swing.border.MatteBorder(null));
        jB12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB12ActionPerformed(evt);
            }
        });
        jPanel2.add(jB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 50));

        jB13.setBackground(new java.awt.Color(255, 217, 33));
        jB13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB13.setBorder(new javax.swing.border.MatteBorder(null));
        jB13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB13ActionPerformed(evt);
            }
        });
        jPanel2.add(jB13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 190, 50));

        jB14.setBackground(new java.awt.Color(255, 217, 33));
        jB14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB14.setBorder(new javax.swing.border.MatteBorder(null));
        jB14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB14ActionPerformed(evt);
            }
        });
        jPanel2.add(jB14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 190, 50));

        jB15.setBackground(new java.awt.Color(255, 217, 33));
        jB15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB15.setBorder(new javax.swing.border.MatteBorder(null));
        jB15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB15ActionPerformed(evt);
            }
        });
        jPanel2.add(jB15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, 50));

        jB20.setBackground(new java.awt.Color(255, 217, 33));
        jB20.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB20.setBorder(new javax.swing.border.MatteBorder(null));
        jB20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB20ActionPerformed(evt);
            }
        });
        jPanel2.add(jB20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 190, 50));

        jB16.setBackground(new java.awt.Color(255, 217, 33));
        jB16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB16.setBorder(new javax.swing.border.MatteBorder(null));
        jB16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB16ActionPerformed(evt);
            }
        });
        jPanel2.add(jB16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 190, 50));

        jB17.setBackground(new java.awt.Color(255, 217, 33));
        jB17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB17.setBorder(new javax.swing.border.MatteBorder(null));
        jB17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 190, 50));

        jB18.setBackground(new java.awt.Color(255, 217, 33));
        jB18.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB18.setBorder(new javax.swing.border.MatteBorder(null));
        jB18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jB18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 190, 50));

        jB19.setBackground(new java.awt.Color(255, 217, 33));
        jB19.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB19.setBorder(new javax.swing.border.MatteBorder(null));
        jB19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB19ActionPerformed(evt);
            }
        });
        jPanel2.add(jB19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 190, 50));

        jB21.setBackground(new java.awt.Color(255, 189, 68));
        jB21.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB21.setBorder(new javax.swing.border.MatteBorder(null));
        jB21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB21ActionPerformed(evt);
            }
        });
        jPanel2.add(jB21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 190, 50));

        jB22.setBackground(new java.awt.Color(255, 189, 68));
        jB22.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB22.setBorder(new javax.swing.border.MatteBorder(null));
        jB22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB22ActionPerformed(evt);
            }
        });
        jPanel2.add(jB22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 190, 50));

        jB23.setBackground(new java.awt.Color(255, 189, 68));
        jB23.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB23.setBorder(new javax.swing.border.MatteBorder(null));
        jB23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB23ActionPerformed(evt);
            }
        });
        jPanel2.add(jB23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 190, 50));

        jB24.setBackground(new java.awt.Color(255, 189, 68));
        jB24.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB24.setBorder(new javax.swing.border.MatteBorder(null));
        jB24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB24ActionPerformed(evt);
            }
        });
        jPanel2.add(jB24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 190, 50));

        jB25.setBackground(new java.awt.Color(255, 189, 68));
        jB25.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB25.setBorder(new javax.swing.border.MatteBorder(null));
        jB25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB25ActionPerformed(evt);
            }
        });
        jPanel2.add(jB25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 190, 50));

        jB26.setBackground(new java.awt.Color(255, 189, 68));
        jB26.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB26.setBorder(new javax.swing.border.MatteBorder(null));
        jB26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB26ActionPerformed(evt);
            }
        });
        jPanel2.add(jB26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 190, 50));

        jB27.setBackground(new java.awt.Color(255, 189, 68));
        jB27.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB27.setBorder(new javax.swing.border.MatteBorder(null));
        jB27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB27ActionPerformed(evt);
            }
        });
        jPanel2.add(jB27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 190, 50));

        jB28.setBackground(new java.awt.Color(255, 189, 68));
        jB28.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB28.setBorder(new javax.swing.border.MatteBorder(null));
        jB28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB28ActionPerformed(evt);
            }
        });
        jPanel2.add(jB28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 190, 50));

        jB29.setBackground(new java.awt.Color(255, 189, 68));
        jB29.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB29.setBorder(new javax.swing.border.MatteBorder(null));
        jB29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB29ActionPerformed(evt);
            }
        });
        jPanel2.add(jB29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 190, 50));

        jB30.setBackground(new java.awt.Color(255, 189, 68));
        jB30.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jB30.setBorder(new javax.swing.border.MatteBorder(null));
        jB30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jB30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB30ActionPerformed(evt);
            }
        });
        jPanel2.add(jB30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 190, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        nameString[0]="";
        nameString[1]="";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_closeDialog

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nameString[0]="";
        nameString[1]="";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB29ActionPerformed
   
        JD C = new JD(new java.awt.Frame(), true);
        int i = C.setName("Red","White","R+W");
        String choice="";
        if(i==1){choice="(R)";}
        else if(i==2){choice="(W)";}
        else if(i==3){choice=" (Red&White)";}
        if(i!=-1){
            nameString[0]="Rav"+choice;
            nameString[1]="Rav"+choice;
        }
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB29ActionPerformed

    private void jB28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB28ActionPerformed
      
        nameString[0]="Brioche";
        nameString[1]="Brioche";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB28ActionPerformed

    private void jB27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB27ActionPerformed
       
        nameString[0]="Asian";
        nameString[1]="Asian";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB27ActionPerformed

    private void jB26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB26ActionPerformed
   
        nameString[0]="Napoleon";
        nameString[1]="Napoleon";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB26ActionPerformed

    private void jB30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB30ActionPerformed
     
        nameString[0]="Lamb";
        nameString[1]="Lamb";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB30ActionPerformed

    private void jB25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB25ActionPerformed

        nameString[0]="Fisherman";
        nameString[1]="FM";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB25ActionPerformed

    private void jB24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB24ActionPerformed
       
        nameString[0]="Salmon";
        nameString[1]="Salmon";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB24ActionPerformed

    private void jB23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB23ActionPerformed
       
        nameString[0]="Opaka";
        nameString[1]="Opaka";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB23ActionPerformed

    private void jB22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB22ActionPerformed
 
        nameString[0]="Hen";
        nameString[1]="Hen";
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB22ActionPerformed

    private void jB21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB21ActionPerformed

        
        JD C = new JD(new java.awt.Frame(), true);
        int i = C.setName("Veggie","Chicken","Seafood");
        String choice="";
        String choice1="";
        if(i==1){choice="(V)";choice1=" (Veggie)";}
        else if(i==2){choice="(C)";choice1=" (Chicken)";}
        else if(i==3){choice="(S)";choice1=" (Seafood)";}
        if(i!=-1){
            
            nameString[0]="Lao Pie"+choice1;
            nameString[1]="LaoPie"+choice;

        }
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB21ActionPerformed

    private void jB16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB16ActionPerformed

        nameString[0]="Linguini";
        nameString[1]="ML";
 
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB16ActionPerformed

    private void jB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB15ActionPerformed

        nameString[0]="Khao Soi(seafood)";
        nameString[1]="KaoSoi(S)";
 
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB15ActionPerformed

    private void jB14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB14ActionPerformed

        nameString[0]="Classic Pasta(seafood)";
        nameString[1]="Classic.Pasta(S)";
      setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB14ActionPerformed

    private void jB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB13ActionPerformed

        nameString[0]="Garlic Shrimp Pasta";
        nameString[1]="G.S.Pasta";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB13ActionPerformed

    private void jB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB12ActionPerformed

        nameString[0]="House Pasta(seafood)";
        nameString[1]="HS.Pasta(S)";
 
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB12ActionPerformed

    private void jB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB11ActionPerformed

        nameString[0]="Southeast Pasta(seafood)";
        nameString[1]="South(S)";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB11ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed

    }//GEN-LAST:event_jB2ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        nameString[0]="Lobster PadThai";
        nameString[1]="Lobster PadThai";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB19ActionPerformed
        nameString[0]="Clam";
        nameString[1]="Clam";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB19ActionPerformed

    private void jB20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB20ActionPerformed
        nameString[0]="Special Rav(Crab)";
        nameString[1]="SP.Crab";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jB20ActionPerformed
    
    
    

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB10;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB12;
    private javax.swing.JButton jB13;
    private javax.swing.JButton jB14;
    private javax.swing.JButton jB15;
    private javax.swing.JButton jB16;
    private javax.swing.JButton jB17;
    private javax.swing.JButton jB18;
    private javax.swing.JButton jB19;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB20;
    private javax.swing.JButton jB21;
    private javax.swing.JButton jB22;
    private javax.swing.JButton jB23;
    private javax.swing.JButton jB24;
    private javax.swing.JButton jB25;
    private javax.swing.JButton jB26;
    private javax.swing.JButton jB27;
    private javax.swing.JButton jB28;
    private javax.swing.JButton jB29;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB30;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables


    private String[] nameString= new String[2];
}
