package com.vinpos.pos;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.util.Calendar;
import javax.swing.JButton;
/**
 *
 * @author sd
 */
public class MoveTable extends java.awt.Dialog {

    /**
     * Creates new form MoveTable
     */
    public MoveTable(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
    }

    public String run(Integer[] i){
        updateColor(i);
        //String[] s =s2.loadTotalFromJJTemp();
        //jLabel2.setText(""+Double.parseDouble(s[0]));
        this.setVisible(true);
        return tableNum;
    }
    public String run2(Integer[] i){
        updateColor2(i);
        this.setVisible(true);
        return tableNum;
    }
    public void setJlabel(String s){
        jLabel1.setText(s);
    }
    
    

    public void updateColor(Integer[] i){
        if(i[0 ]>0){      A1.setBackground(Color.GREEN);}else{     A1.setEnabled(false);}
        if(i[1 ]>0){      A2.setBackground(Color.GREEN);}else{     A2.setEnabled(false);}
        if(i[2 ]>0){      B1.setBackground(Color.GREEN);}else{     B1.setEnabled(false);}
        if(i[3 ]>0){      B2.setBackground(Color.GREEN);}else{     B2.setEnabled(false);}
        if(i[4 ]>0){      B3.setBackground(Color.GREEN);}else{     B3.setEnabled(false);}
        if(i[5 ]>0){      B4.setBackground(Color.GREEN);}else{     B4.setEnabled(false);}
        if(i[6 ]>0){      C1.setBackground(Color.GREEN);}else{     C1.setEnabled(false);}
        if(i[7 ]>0){      C2.setBackground(Color.GREEN);}else{     C2.setEnabled(false);}
        if(i[8 ]>0){      C3.setBackground(Color.GREEN);}else{     C3.setEnabled(false);}
        if(i[9 ]>0){      C4.setBackground(Color.GREEN);}else{     C4.setEnabled(false);}
        if(i[10]>0){      C5.setBackground(Color.GREEN);}else{     C5.setEnabled(false);}
        if(i[11]>0){      T1.setBackground(Color.GREEN);}else{     T1.setEnabled(false);}
        if(i[12]>0){      T10.setBackground(Color.GREEN);}else{    T10.setEnabled(false);}
        if(i[13]>0){      T9.setBackground(Color.GREEN);}else{     T9.setEnabled(false);}
    }
    public void updateColor2(Integer[] i){
        if(i[0 ]>0){     A1.setEnabled(false);}else{     A1.setBackground(Color.YELLOW);}
        if(i[1 ]>0){     A2.setEnabled(false);}else{     A2.setBackground(Color.YELLOW);}
        if(i[2 ]>0){     B1.setEnabled(false);}else{     B1.setBackground(Color.YELLOW);}
        if(i[3 ]>0){     B2.setEnabled(false);}else{     B2.setBackground(Color.YELLOW);}
        if(i[4 ]>0){     B3.setEnabled(false);}else{     B3.setBackground(Color.YELLOW);}
        if(i[5 ]>0){     B4.setEnabled(false);}else{     B4.setBackground(Color.YELLOW);}
        if(i[6 ]>0){     C1.setEnabled(false);}else{     C1.setBackground(Color.YELLOW);}
        if(i[7 ]>0){     C2.setEnabled(false);}else{     C2.setBackground(Color.YELLOW);}
        if(i[8 ]>0){     C3.setEnabled(false);}else{     C3.setBackground(Color.YELLOW);}
        if(i[9 ]>0){     C4.setEnabled(false);}else{     C4.setBackground(Color.YELLOW);}
        if(i[10]>0){     C5.setEnabled(false);}else{     C5.setBackground(Color.YELLOW);}
        if(i[11]>0){     T1.setEnabled(false);}else{ T1.setBackground(Color.YELLOW);}
        if(i[12]>0){     T10.setEnabled(false);}else{T10.setBackground(Color.YELLOW);}
        if(i[13]>0){     T9.setEnabled(false);}else{ T9.setBackground(Color.YELLOW);}
    }
    public Boolean isClose(){
        return quit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        A2 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        T9 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        T1 = new javax.swing.JButton();
        T10 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A2.setText("A2");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel1.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 110, 60));

        B1.setText("B1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 70, 80));

        T9.setText("T9");
        T9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T9ActionPerformed(evt);
            }
        });
        jPanel1.add(T9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 110, 60));

        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 110, 60));

        T1.setText("T1");
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 172, 76, 90));

        T10.setText("T10");
        T10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T10ActionPerformed(evt);
            }
        });
        jPanel1.add(T10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 120, 60));

        C4.setText("C4");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        jPanel1.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 70, 80));

        C5.setText("C5");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        jPanel1.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 70, 70));

        C2.setText("C2");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel1.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 70, 80));

        C3.setText("C3");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 70, 80));

        B3.setText("B3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 70, 80));

        B2.setText("B2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 70, 80));

        B4.setText("B4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 70, 80));

        C1.setText("C1");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 70, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select A Table that You want to Move");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 650, 152));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 102));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, 97));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        quit =false;
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_closeDialog

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        tableNum = "A2";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_A2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
       tableNum = "B1";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_B1ActionPerformed

    private void T9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T9ActionPerformed
        tableNum = "T9";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_T9ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
       tableNum = "A1";
 
        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_A1ActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
       tableNum = "T1";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_T1ActionPerformed

    private void T10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T10ActionPerformed
      tableNum = "T10";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_T10ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        tableNum = "C4";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        tableNum = "C5";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_C5ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
       tableNum = "C2";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
      tableNum = "C3";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_C3ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        tableNum = "B3";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_B3ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
       tableNum = "B2";
        
       setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_B2ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        tableNum = "B4";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_B4ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
       tableNum = "C1";

        setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_C1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       quit =false;
       setVisible(false);
       setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton T1;
    private javax.swing.JButton T10;
    private javax.swing.JButton T9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private String tableNum = "";
    private JButton tableButton = new JButton();
    private Boolean quit=true;
    private SortOrder s2 = new SortOrder();
    private Calendar theTime;
}
