package com.vinpos.pos;


import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Hashtable;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinson
 */
public class NewOrderPanel extends javax.swing.JDialog {

    /**
     * Creates new form EDITDialog
     */
    
    public NewOrderPanel(java.awt.Frame parent, boolean modal, MyQuery myQ_) {
        super(parent, modal);
        initComponents();
        myQ = myQ_;
        isEmpty = false;
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
    }
    public boolean run(int tableID_, int userID_){
        tableID=tableID_;
        userID=userID_;
        this.setVisible(true);
        return isUpdated;       
    }
    
    
//    public void updateDB(){
//        Connection co = null;
//        PreparedStatement ps= null;
//        ResultSet rs= null;
//        
//        
//        String type = "secondCourse";
//        
//        try{
//            JsonSimple js = new JsonSimple();
//            co = myconnection.getConnection(js);
//            
//            String firstcourse ="";
//            String secondcourse ="";
//            String thirdcourse ="";
//            String seafood ="";
//            String other ="";
//            String drink="";
//            String dessert ="";
//            
//          
//            
//            String dateTime = this.getDateTime();
//            Double[] TDC = myQ.getTipDiscountCouponAtSubtable(tableID, Integer.parseInt("1"));
//            
//            String query = "INSERT `R`.`order` SET `tip`='"+TDC[0]+"', `discount`='"+TDC[1]+"', `coupon`='"+TDC[2]+"', `name`=?, `firstCourse`='"+firstcourse+"', `secondCourse`=?, `thirdCourse`='"+thirdcourse+"', `seafood`='"+seafood+"', `dessert`='"+dessert+"', `drink`='"+drink+"', `other`=?, `price`=?, `quantity`='1', `position`='1', `note`='', `type`='"+type+"', `tid`='"+tableID+"', `aid`='"+userID+"', `subtable`='1', `time_in`='"+dateTime+"'"; 
//            
//            ps = co.prepareStatement(query);
//            ps.setString(1, text1.getText());
//            ps.setString(2, text1.getText());
//            ps.setString(3, "");
//            ps.setString(4, text3.getText());
//            ps.executeUpdate();
//            isUpdated=true;
//            
//        }catch(Exception e){
//            System.out.println("error occur when update:"+e);
//        }finally{
//         
//            if (rs != null) {
//            try {
//                rs.close();
//            } catch (SQLException e) { /* ignored */}
//            }
//            if (ps != null) {
//                try {
//                    ps.close();
//                } catch (SQLException e) { /* ignored */}
//            }
//            if (co != null) {
//                try {
//                    co.close();
//                } catch (SQLException e) { /* ignored */}
//            }
//        }
//        
//    }//end of editselect
    public void updateDB(){
        Hashtable<String, String> data = new Hashtable<String, String>();
        data.put("name",text1.getText());
        data.put("price",  text3.getText());
        myQ.insertASimpleOrder(tableID, userID, data);
    }
    
    public String getDateTime(){
        theTime = Calendar.getInstance();
        NumberFormat myFormat = new DecimalFormat("#00");
        int a = theTime.get(Calendar.YEAR);
        int b = theTime.get(Calendar.MONTH)+1;
        String a1 =myFormat.format(b);
        int c = theTime.get(Calendar.DATE);
        String a2=myFormat.format(c);
        int d = theTime.get(Calendar.HOUR_OF_DAY);
        String a3=myFormat.format(d);
        int e = theTime.get(Calendar.MINUTE);
        String a4=myFormat.format(e);
        int f = theTime.get(Calendar.SECOND);
        String a5=myFormat.format(f);
        
        String dateTime= a+"-"+a1+"-"+a2+" "+a3+"-"+a4+"-"+a5;
        
        return dateTime;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        text3 = new javax.swing.JFormattedTextField();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Name");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("price");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        text1.setForeground(new java.awt.Color(204, 204, 204));
        text1.setText("Enter Order Name Here");
        text1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text1MousePressed(evt);
            }
        });
        text1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text1FocusGained(evt);
            }
        });
        text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text1KeyPressed(evt);
            }
        });
        jPanel1.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 530, 50));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 140, 90));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, 90));

        text3.setForeground(new java.awt.Color(204, 204, 204));
        text3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        text3.setText("0.00");
        text3.setToolTipText("0.00");
        text3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text3ActionPerformed(evt);
            }
        });
        text3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                text3FocusGained(evt);
            }
        });
        jPanel1.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(text1.getText().equals("")){ 
            text1.setText("New Order");
                
        }
        
        if(text3.getText().equals("")){
            text3.setText("0.00");
        }
        
        
        this.updateDB();
        isUpdated = true;
        this.setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text3ActionPerformed

    private void text3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text3FocusGained
        text3.setText("");
        text3.setForeground(Color.black);
    }//GEN-LAST:event_text3FocusGained
    
    private void text1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text1KeyPressed
        if(!isEmpty){
            text1.setText("");
            text1.setForeground(Color.black);
            isEmpty =true;
        }
        
    }//GEN-LAST:event_text1KeyPressed

    private void text1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_text1FocusGained
       
    }//GEN-LAST:event_text1FocusGained

    private void text1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text1MouseEntered
        
    }//GEN-LAST:event_text1MouseEntered

    private void text1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text1MousePressed
        if(!isEmpty){
            text1.setText("");
            text1.setForeground(Color.black);
            isEmpty =true;
        }
    }//GEN-LAST:event_text1MousePressed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text1;
    private javax.swing.JFormattedTextField text3;
    // End of variables declaration//GEN-END:variables
    private Calendar theTime;
    int tableID;
    int userID;
    private boolean isUpdated = false;
    private boolean isEmpty;
    private MyQuery myQ;
    
}
