package com.vinpos.pos;


import com.vinpos.connection.PrintConn;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinson
 */
public class PrintOptionPanel extends javax.swing.JDialog {

    /**
     * Creates new form printOptionPanel
     */
    private JsonSimple databasePrinterSetting = new JsonSimple();
    
    public PrintOptionPanel(java.awt.Frame parent, boolean modal, MyQuery myQ_) {
        super(parent, modal);
        initComponents();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        myQ = myQ_;
        
    }
    public void setUpTableIDandUserID(int tid, int uid){
        tableID = tid;
        userID= uid;
    }
    public void setVisible(){
        this.setVisible(true);
    }
    public void sendPrintOrderToServer(String orderString){
        
        PrintConn con = new PrintConn();
        con.createSocket();
        Socket pritnerSocket = con.giveMePrinterSocket();

        try{
            System.out.println("Print Order initial");
            System.out.println("OrderString:"+orderString);
            System.out.println("test socket connection 1");
            DataOutputStream outToServer = new DataOutputStream(pritnerSocket.getOutputStream());
            System.out.println("test outToserver connection 2");
            outToServer.writeBytes(orderString+"\n");  // set out message
            System.out.println("test weiteByetes connection 3");
            System.out.println("Print Order Sent");

            BufferedReader inFromServer = new BufferedReader(new InputStreamReader(pritnerSocket.getInputStream()));
            System.out.println("SERVER Responds: " + inFromServer.readLine());
            inFromServer.close();
            con.closeSocket();

        }catch(Exception e){

            System.out.println("Table.sendPrintOrderToServer() Exception Occured - Break");
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton1.setText("Print food+seafood");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton2.setText("Print Seafood");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton3.setText("Print food");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton4.setText("Print cake");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jButton5.setText("Print drink");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
            .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JsonSimple jsonSimple = new JsonSimple();
        PrintCheckJJStyle p = new PrintCheckJJStyle(myQ);
        if(jsonSimple.isThisPrintServer){
            p.print(tableID,userID,PRINT_ALL,myQ);
                
        }else{
            this.sendPrintOrderToServer("kitchen "+ tableID +" "+userID+" "+PRINT_ALL);
        }
        myQ.updateFoodandSeafoodSentTime(tableID);
        myQ.updateFoodandSeafoodSent(tableID);
        int status = 1;
        myQ.updateTableStatus(status,tableID);
        myQ.setTableChecked("NO", tableID);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JsonSimple jsonSimple = new JsonSimple();
        PrintCheckJJStyle p = new PrintCheckJJStyle(myQ);
        if(jsonSimple.isThisPrintServer){
            p.print(tableID,userID,PRINT_SEAFOOD,myQ);
                
        }else{
            this.sendPrintOrderToServer("kitchen "+ tableID +" "+userID+" "+PRINT_SEAFOOD);
        }
        myQ.updateSeafoodSentTime(tableID);
        myQ.updateSeafoodSent(tableID);
        int status = 1;
        myQ.updateTableStatus(status,tableID);
        myQ.setTableChecked("NO", tableID);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JsonSimple jsonSimple = new JsonSimple();
        PrintCheckJJStyle p = new PrintCheckJJStyle(myQ);
        if(jsonSimple.isThisPrintServer){
            p.print(tableID,userID,PRINT_FOOD,myQ);
                
        }else{
            this.sendPrintOrderToServer("kitchen "+ tableID +" "+userID+" "+PRINT_FOOD);
        }
        System.out.print("PRINT_TYPE:"+PRINT_FOOD);
        myQ.updateFoodSentTime(tableID);
        myQ.updateFoodSent(tableID);
        int status = 1;
        myQ.updateTableStatus(status,tableID);
        myQ.setTableChecked("NO", tableID);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JsonSimple jsonSimple = new JsonSimple();
        PrintCheckJJStyle p = new PrintCheckJJStyle(myQ);
        if(jsonSimple.isThisPrintServer){
            p.print(tableID,userID,PRINT_DRINK,myQ);
                
        }else{
            this.sendPrintOrderToServer("kitchen "+ tableID +" "+userID+" "+PRINT_DRINK);
        }
        myQ.updateDrinkSentTime(tableID);
        myQ.updateDrinkSent(tableID);
        int status = 1;
        myQ.updateTableStatus(status,tableID);
        myQ.setTableChecked("NO", tableID);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JsonSimple jsonSimple = new JsonSimple();
        PrintCheckJJStyle p = new PrintCheckJJStyle(myQ);
        if(jsonSimple.isThisPrintServer){
            p.print(tableID,userID,PRINT_DESSERT,myQ);
                
        }else{
            this.sendPrintOrderToServer("kitchen "+ tableID +" "+userID+" "+PRINT_DESSERT);
        }
        myQ.updateDessertSentTime(tableID);
        myQ.updateDessertSent(tableID);
        int status = 1;
        myQ.updateTableStatus(status,tableID);
        myQ.setTableChecked("NO", tableID);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private MyQuery myQ;
    private int tableID;
    private int userID;
    
    private static int DEFAULT_PRINT =1;
    private static int PRINT_ALL     =2;
    private static int PRINT_SEAFOOD =3;
    private static int PRINT_FOOD    =4;
    private static int PRINT_DRINK   =5;
    private static int PRINT_DESSERT =6;
    
}
