/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.vinpos.pos.CakeOrderPanel;

import com.vinpos.pos.MyQuery;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JButton;

/**
 *
 * @author jj
 */
public class SelectCake extends javax.swing.JDialog {

    /**
     * Creates new form SelectCake
     */
    private SelectSize dialog;
    private SelectFavor favor;
    private SelectLargeQuantity quantity;
    private String cakename;
    private String cakesize;
    private Double cakeprice;
    private MyQuery myQ;
    private int wid;
    private NumberFormat moneyVariable;
    public SelectCake(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        dialog = new SelectSize(new javax.swing.JFrame(), true);
        favor = new SelectFavor(new javax.swing.JFrame(), true);
        quantity = new SelectLargeQuantity(new javax.swing.JFrame(), true);
        moneyVariable = NumberFormat.getCurrencyInstance(Locale.US);
        cakename="";
        cakesize="";
        cakeprice=0.00;
        wid=0;
        jTextField3.setValue(0.00);
        
    }
    public void setWid(int wid_, MyQuery myQ_){
        wid=wid_;
        myQ=myQ_;
    }
    public void loadData(){
        Object[] temp = myQ.getWholeCakeOrderWithWid(wid);
        jTextField1.setText((String)temp[0]);
        jTextField2.setText((String)temp[1]);
        jTextField3.setValue((Double)temp[9]);
       

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton149 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Size");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 100, -1));

        jLabel2.setForeground(new java.awt.Color(153, 51, 255));
        jLabel2.setText("Price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 51, 255));
        jLabel3.setText("Cake Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 110));

        jButton113.setBackground(new java.awt.Color(204, 0, 204));
        jButton113.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton113.setText("Fruit Basket");
        jButton113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton113ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 160, 48));

        jButton114.setBackground(new java.awt.Color(153, 153, 255));
        jButton114.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton114.setText("Apple Tart");
        jButton114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton114ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 170, 40));

        jButton115.setBackground(new java.awt.Color(153, 153, 255));
        jButton115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton115.setText("Citrus Tart");
        jButton115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton115ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton115, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 170, 40));

        jButton116.setBackground(new java.awt.Color(153, 153, 255));
        jButton116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton116.setText("Pear Tart");
        jButton116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton116ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton116, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 170, 40));

        jButton118.setBackground(new java.awt.Color(153, 153, 255));
        jButton118.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton118.setText("Walnut Tart");
        jButton118.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton118ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton118, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, 170, 40));

        jButton119.setBackground(new java.awt.Color(204, 0, 204));
        jButton119.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton119.setText("Frou Frou");
        jButton119.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton119ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton119, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 160, 48));

        jButton120.setBackground(new java.awt.Color(102, 255, 102));
        jButton120.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton120.setText("Guava Mousse");
        jButton120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton120ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton120, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 210, 48));

        jButton121.setBackground(new java.awt.Color(255, 153, 0));
        jButton121.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton121.setText("Cherry CheeseCake");
        jButton121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton121ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton121, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, 48));

        jButton132.setBackground(new java.awt.Color(102, 255, 102));
        jButton132.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton132.setText("Chocolate Hazanut");
        jButton132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton132ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton132, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 210, 48));

        jButton133.setBackground(new java.awt.Color(153, 153, 255));
        jButton133.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton133.setText("Fruity Tart");
        jButton133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton133ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton133, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 170, 40));

        jButton134.setBackground(new java.awt.Color(102, 255, 102));
        jButton134.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton134.setText("Banana Haupia");
        jButton134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton134ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton134, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 48));

        jButton135.setBackground(new java.awt.Color(255, 153, 0));
        jButton135.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton135.setText("GreenTea CheeseCake");
        jButton135.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton135ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton135, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 220, 48));

        jButton136.setBackground(new java.awt.Color(255, 153, 0));
        jButton136.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton136.setText("Mocha CheeseCake");
        jButton136.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton136ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton136, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, 48));

        jButton137.setBackground(new java.awt.Color(255, 153, 0));
        jButton137.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton137.setText("BlueBerry CheeseCake");
        jButton137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton137ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton137, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 220, 48));

        jButton138.setBackground(new java.awt.Color(255, 153, 0));
        jButton138.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton138.setText("Strawberry CheeseCake");
        jButton138.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton138ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton138, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 220, 48));

        jButton139.setBackground(new java.awt.Color(102, 255, 102));
        jButton139.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton139.setText("ShortCake");
        jButton139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton139ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton139, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 210, 48));

        jButton140.setBackground(new java.awt.Color(102, 255, 102));
        jButton140.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton140.setText("Lilikoi Mousse");
        jButton140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton140ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton140, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 210, 48));

        jButton141.setBackground(new java.awt.Color(102, 255, 102));
        jButton141.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton141.setText("Mango Peach");
        jButton141.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton141ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton141, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 210, 48));

        jButton142.setBackground(new java.awt.Color(102, 255, 102));
        jButton142.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton142.setText("LeCafe");
        jButton142.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton142ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton142, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 210, 48));

        jButton143.setBackground(new java.awt.Color(102, 255, 102));
        jButton143.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton143.setText("Chestnut");
        jButton143.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton143ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton143, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 210, 48));

        jButton144.setBackground(new java.awt.Color(102, 255, 102));
        jButton144.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton144.setText("IceDrop");
        jButton144.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton144ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton144, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 210, 48));

        jButton145.setBackground(new java.awt.Color(153, 255, 153));
        jButton145.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton145.setText("Chocolate Raspberry");
        jButton145.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton145ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton145, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 210, 48));

        jButton146.setBackground(new java.awt.Color(204, 0, 204));
        jButton146.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton146.setText("Tiramisu");
        jButton146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton146ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton146, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 160, 48));

        jButton147.setBackground(new java.awt.Color(204, 0, 204));
        jButton147.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton147.setText("Mocha Opera");
        jButton147.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton147ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton147, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 160, 48));

        jButton148.setBackground(new java.awt.Color(0, 153, 153));
        jButton148.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton148.setForeground(new java.awt.Color(51, 51, 51));
        jButton148.setText("Croquembouce");
        jButton148.setToolTipText("");
        jButton148.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton148ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton148, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 160, 48));

        jButton150.setBackground(new java.awt.Color(102, 255, 102));
        jButton150.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton150.setText("GreenTea Mousse");
        jButton150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton150ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton150, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 210, 48));

        jButton151.setBackground(new java.awt.Color(204, 0, 204));
        jButton151.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton151.setText("Peanut");
        jButton151.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton151ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton151, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 160, 48));

        jButton152.setBackground(new java.awt.Color(102, 255, 102));
        jButton152.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton152.setText("Black Current");
        jButton152.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton152ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton152, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, 48));

        jButton154.setBackground(new java.awt.Color(255, 153, 0));
        jButton154.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton154.setText("NY CheeseCake");
        jButton154.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton154ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton154, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 220, 48));

        jButton156.setBackground(new java.awt.Color(153, 153, 255));
        jButton156.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton156.setText("Raspberry Tart");
        jButton156.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton156ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton156, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 170, 40));

        jButton157.setBackground(new java.awt.Color(153, 153, 255));
        jButton157.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton157.setText("Almondine");
        jButton157.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton157ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton157, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 170, 40));

        jButton158.setBackground(new java.awt.Color(102, 255, 102));
        jButton158.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton158.setText("RedVelvet");
        jButton158.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton158ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton158, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 210, 48));

        jButton160.setBackground(new java.awt.Color(153, 153, 255));
        jButton160.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton160.setText("Blue Berry Tart");
        jButton160.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton160ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton160, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 170, 40));

        jButton161.setBackground(new java.awt.Color(153, 153, 255));
        jButton161.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton161.setText("Lime Tart");
        jButton161.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton161ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton161, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 170, 40));

        jButton162.setBackground(new java.awt.Color(153, 153, 255));
        jButton162.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton162.setText("Mac Nut Tart");
        jButton162.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton162ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton162, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 170, 40));

        jButton163.setBackground(new java.awt.Color(153, 153, 255));
        jButton163.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton163.setText("Plum Tart");
        jButton163.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton163ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton163, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 170, 40));

        jButton164.setBackground(new java.awt.Color(153, 153, 255));
        jButton164.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton164.setText("Apricot Tart");
        jButton164.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton164ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton164, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 170, 40));

        jButton165.setBackground(new java.awt.Color(153, 153, 255));
        jButton165.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton165.setText("Pecan Tart");
        jButton165.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton165ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton165, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 170, 40));

        jButton166.setBackground(new java.awt.Color(102, 255, 102));
        jButton166.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton166.setText("Cherry Brandy");
        jButton166.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton166ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton166, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 210, 48));

        jButton167.setBackground(new java.awt.Color(102, 255, 102));
        jButton167.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton167.setText("Double Chocolate");
        jButton167.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton167ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton167, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 210, 48));

        jButton16.setBackground(new java.awt.Color(102, 0, 102));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 204, 255));
        jButton16.setText("Rapberry Pyramid");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 210, 50));

        jButton46.setBackground(new java.awt.Color(102, 0, 102));
        jButton46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton46.setForeground(new java.awt.Color(255, 204, 255));
        jButton46.setText("Chocolate Pyramid");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 210, 50));

        jButton174.setBackground(new java.awt.Color(255, 153, 0));
        jButton174.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton174.setText("Pumkin CheeseCake");
        jButton174.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton174ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton174, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 220, 48));

        jButton117.setBackground(new java.awt.Color(0, 153, 153));
        jButton117.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton117.setForeground(new java.awt.Color(51, 51, 51));
        jButton117.setText("Gallette De Rois");
        jButton117.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton117ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton117, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 160, 48));

        jButton182.setBackground(new java.awt.Color(255, 153, 0));
        jButton182.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton182.setText("Guava CheeseCake");
        jButton182.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton182ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton182, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 48));

        jButton180.setBackground(new java.awt.Color(255, 153, 0));
        jButton180.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton180.setText("Lilikoi CheeseCake");
        jButton180.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton180ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton180, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 48));

        jButton181.setBackground(new java.awt.Color(153, 153, 255));
        jButton181.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton181.setText("Mac Rum Tart");
        jButton181.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton181ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton181, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 170, 40));

        jButton176.setBackground(new java.awt.Color(204, 0, 204));
        jButton176.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton176.setText("Black Forest");
        jButton176.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton176ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton176, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 160, 48));

        jButton122.setBackground(new java.awt.Color(0, 153, 153));
        jButton122.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton122.setForeground(new java.awt.Color(51, 51, 51));
        jButton122.setText("Bush De Noel");
        jButton122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton122ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton122, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 160, 48));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jButton2.setText("Save");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 190, 110));

        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 260, 110));

        jButton149.setBackground(new java.awt.Color(153, 255, 153));
        jButton149.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton149.setText("Fruit Cake");
        jButton149.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton149ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton149, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 210, 48));

        jButton17.setBackground(new java.awt.Color(255, 255, 255));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(102, 102, 255));
        jButton17.setText("1 Tier Wedding Cake");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 210, 50));

        jButton47.setBackground(new java.awt.Color(255, 255, 255));
        jButton47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton47.setForeground(new java.awt.Color(102, 102, 255));
        jButton47.setText("3 Tier Wedding Cake");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 210, 50));

        jButton48.setBackground(new java.awt.Color(255, 255, 255));
        jButton48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton48.setForeground(new java.awt.Color(102, 102, 255));
        jButton48.setText("2 Tier Wedding Cake");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 210, 50));

        jButton49.setBackground(new java.awt.Color(255, 255, 255));
        jButton49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton49.setForeground(new java.awt.Color(102, 102, 255));
        jButton49.setText("4 Tier Wedding Cake");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 210, 50));

        jTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTextField3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 180, 110));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Mini Pastry");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 220, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Stawberry Dip");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton113ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 38.00, "Round 10\"", 46.00, "Round 12\"", 53.00, "", 0.00, "", 0.00, "", 0.00, "",0.00);
    }//GEN-LAST:event_jButton113ActionPerformed

    private void jButton114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton114ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton114ActionPerformed

    private void jButton115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton115ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton115ActionPerformed

    private void jButton116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton116ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton116ActionPerformed

    private void jButton118ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton118ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton118ActionPerformed

    private void jButton119ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton119ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 38.00, "Round 10\"", 43.00, "Quarter Sheet", 53.00, "Round 12\"", 60.00, "Square 12\"x12\"", 63.00, "Half Sheet", 95.00, "Full Sheet", 210.00);
    }//GEN-LAST:event_jButton119ActionPerformed

    private void jButton120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton120ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
       
    }//GEN-LAST:event_jButton120ActionPerformed

    private void jButton121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton121ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton121ActionPerformed

    private void jButton132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton132ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton132ActionPerformed

    private void jButton133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton133ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton133ActionPerformed

    private void jButton134ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton134ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton134ActionPerformed

    private void jButton135ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton135ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton135ActionPerformed

    private void jButton136ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton136ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton136ActionPerformed

    private void jButton137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton137ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton137ActionPerformed

    private void jButton138ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton138ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton138ActionPerformed

    private void jButton139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton139ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton139ActionPerformed

    private void jButton140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton140ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton140ActionPerformed

    private void jButton141ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton141ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton141ActionPerformed

    private void jButton142ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton142ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton142ActionPerformed

    private void jButton143ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton143ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton143ActionPerformed

    private void jButton144ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton144ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton144ActionPerformed

    private void jButton145ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton145ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton145ActionPerformed

    private void jButton146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton146ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton146ActionPerformed

    private void jButton147ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton147ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton147ActionPerformed

    private void jButton148ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton148ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "1 foot", 135.00, "1.5 foot", 175.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00, "",0.00);

    }//GEN-LAST:event_jButton148ActionPerformed

    private void jButton150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton150ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton150ActionPerformed

    private void jButton151ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton151ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton151ActionPerformed

    private void jButton152ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton152ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton152ActionPerformed

    private void jButton154ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton154ActionPerformed
       this.selectSize(((JButton) evt.getSource()).getText(), "Pyramid Sharp 5\"", 28.00, "Pyramid Shape 7\"", 35.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00, "",0.00);

    }//GEN-LAST:event_jButton154ActionPerformed

    private void jButton157ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton157ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton157ActionPerformed

    private void jButton158ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton158ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton158ActionPerformed

    private void jButton160ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton160ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 32.00, "Round 10\"", 39.00, "Round 12\"", 49.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton160ActionPerformed

    private void jButton161ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton161ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton161ActionPerformed

    private void jButton162ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton162ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton162ActionPerformed

    private void jButton163ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton163ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton163ActionPerformed

    private void jButton164ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton164ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton164ActionPerformed

    private void jButton165ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton165ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton165ActionPerformed

    private void jButton166ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton166ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);

    }//GEN-LAST:event_jButton166ActionPerformed

    private void jButton167ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton167ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton167ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "5\"", 25.00, "7\"", 35.00, "8.5\"", 55.00, "10\"", 85.00, "12\"", 145.00, "", 0.00, "", 0.00);

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "5\"", 25.00, "7\"", 35.00, "8.5\"", 55.00, "10\"", 85.00, "12\"", 145.00, "", 0.00, "", 0.00);

    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton174ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton174ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton174ActionPerformed

    private void jButton117ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton117ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00);

    }//GEN-LAST:event_jButton117ActionPerformed

    private void jButton182ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton182ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton182ActionPerformed

    private void jButton180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton180ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 35.00, "Round 10\"", 45.00, "Round 12\"", 50.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);

    }//GEN-LAST:event_jButton180ActionPerformed

    private void jButton181ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton181ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 28.00, "Round 10\"", 35.00, "Round 12\"", 45.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
    }//GEN-LAST:event_jButton181ActionPerformed

    private void jButton176ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton176ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton176ActionPerformed

    private void jButton122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton122ActionPerformed
        favor.setFavor("Raspberry","Mocha","Chocolate","","","","");
        favor.setVisible(true);
        String selectedfavor = favor.getCakeFavor();
        if(!selectedfavor.equals(""))this.selectSize(((JButton) evt.getSource()).getText()+"("+selectedfavor+")", "length 12\"", 45.00, "length 18\"", 55.00, "length 24\"", 75.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00);

    }//GEN-LAST:event_jButton122ActionPerformed

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2MouseEntered

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         jTextField2.validate();
         jTextField1.validate();
         jTextField3.validate();
         cakename=jTextField1.getText();
         cakesize=jTextField2.getText(); 
         Number value = ( Number ) jTextField3.getValue();
         cakeprice=value.doubleValue();
         myQ.updateCakeNameSizePriceOrderWithWID(wid, cakename, cakesize, cakeprice);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton156ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton156ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 32.00, "Round 10\"", 39.00, "Round 12\"", 49.00, "", 0.00, "", 0.00, "", 0.00,"",0.00);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton156ActionPerformed

    private void jButton149ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton149ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "Round 8\"", 30.00, "Round 10\"", 35.00, "Quarter Sheet", 38.00, "Round 12\"", 45.00, "Square 12\"x12\"", 48.00, "Half Sheet", 75.00, "Full Sheet", 175.00);
    }//GEN-LAST:event_jButton149ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "6\"", 48.00, "7\"", 55.50, "8\"", 63.00, "9\"", 65.00, "10\"", 73.00, "12\"", 83.00, "14\"", 98.00);
       
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "6\"x9\"x14\"", 245.00, "7\"x10\"x16\"", 260.00, "8\"x12\"x16\"", 315.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "6\"x8\"", 123.00, "7\"x10\"", 153.00, "8\"x12\"", 163.00, "12\"x16\"", 183.00, "", 0.00, "", 0.00, "", 0.00);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        this.selectSize(((JButton) evt.getSource()).getText(), "6\"x9\"x12\"x16\"", 355.00,"", 0.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00, "", 0.00);
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double price = 1.75;
        quantity.setUnitPrice(price);
        quantity.setVisible(true);
        int quan = quantity.getQuantity();
        jTextField1.setText(((JButton) evt.getSource()).getText());
        jTextField2.setText(quan+"x Pieces");
        jTextField3.setValue(price*quan);
        cakename=((JButton) evt.getSource()).getText();
        cakesize=(quan+"x Pieces");
        cakeprice=price*quan;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Double price = 2.4958;
        quantity.setUnitPrice(price);
        quantity.setVisible(true);
        int quan = quantity.getQuantity();
        jTextField1.setText(((JButton) evt.getSource()).getText());
        jTextField2.setText(quan+"x Pieces");
        jTextField3.setValue(price*quan);
        cakename=((JButton) evt.getSource()).getText();
        cakesize=(quan+"x Pieces");
        cakeprice=price*quan;
    }//GEN-LAST:event_jButton3ActionPerformed

    public void selectSize(String name, String s1, Double p1, String s2, Double p2, String s3, Double p3, String s4, Double p4, String s5, Double p5, String s6, Double p6, String s7, Double p7){
        dialog.setSizeAndPrice(s1,p1,s2,p2,s3,p3,s4,p4,s5,p5,s6,p6,s7,p7);
        dialog.setVisible(true);
        cakeprice=dialog.getCakePrice();
        cakesize=dialog.getCakeSize();
        cakename=name;
        if(cakeprice!=0.00 && !cakesize.equals("")&&!cakename.equals("")){
            jTextField1.setText(cakename);
            jTextField2.setText(cakesize);
            jTextField3.setValue(cakeprice);
            
        }
    }
    public String getCakeSize(){
        if(cakesize.equals("Cake Size") || cakesize.equals("")){
            return "empty";
        }
        return cakesize;
    }
    public Double getCakePrice(){
        if(cakeprice.equals("0.0")|| cakeprice.equals("")){
            return 0.00;
        }
        return cakeprice;
    }
    public String getCakeName(){
        if(cakename.equals("Cake Name")|| cakename.equals("")){
            return "empty";
        }
        return cakename;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JFormattedTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
